serviceHost: localhost
spring:
  datasource:
    url: jdbc:mysql://${serviceHost}:3306/demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: test
  #消息队列配置
  rabbitmq:
    addresses: ${serviceHost}
    username: test
    password: test
    port: 5172
    virtual-host: test_vhost
    publisher-confirms: true
    #    template:
    #      exchange: test.direct
    listener:
      #direct:
      #  acknowledge-mode: manual
      #  prefetch: 3
      #  consumers-per-queue:
      simple:
        #消费者手动回复ack消息
        acknowledge-mode: manual
        #最多同时接收消息数量
        prefetch: 2
  redis:
    host: ${serviceHost}
mybatis:
  type-aliases-package: com.summer.springboot.web.demo.pojo
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true