spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: test
mybatis:
  type-aliases-package: com.summer.springboot.shiro.demo.pojo
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
